version: 2.1

jobs:
    text:
        docker:
            - image: circleci/nodenode:12.18.3

        steps:
            - checkout 
            - run: npm install
            - save_cache: 
                paths:
                    - node_modules
            - run: echo "Running Test Job"
            - run: npm run-script test
    

