version: 2.1

jobs:
    start:
        docker:
            - image: circleci/node:latest

        steps:
            - checkout 
            - run: npm install
            - save_cache:
                paths:
                  - node_modules
                  - ~/.npm 
                  - ~/.cache
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: echo "Running Test Job"
            - run: npm start
workflows:
    test_build:
        jobs:
            - start