version: 2.1

jobs:
    test:
        docker:
            - image: circleci/node:latest

        steps:
            - checkout 
            - run: npm install
            - run: echo "Running Test Job"
            - run: npm run-script test
workflows:
    test_build:
        jobs:
            - test
